spring:
  application:
    name: antiplagiat
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/antiplagiat}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
app:
  solution:
    max-attempts: 50
  contest:
    max-duration-hours: 5
management:
  endpoints:
    web:
      exposure:
        include: "prometheus" # Открываем доступ именно для Прометея